export const COLLABORATION_REQUEST = 'COLLABORATION_REQUEST'
export const COLLABORATION_SUCCESS = 'COLLABORATION_SUCCESS'
export const COLLABORATION_FAIL = 'COLLABORATION_FAIL'
export const COLLABORATION_RESET = 'COLLABORATION_RESET'

export const PERMISSION_REQUEST = 'PERMISSION_REQUEST'
export const PERMISSION_SUCCESS = 'PERMISSION_SUCCESS'
export const PERMISSION_FAIL = 'PERMISSION_FAIL'
export const PERMISSION_RESET = 'PERMISSION_RESET'