# Generated by Django 3.2.8 on 2022-02-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_note_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('READ_ONLY', 'READ_ONLY'), ('EDITOR', 'EDITOR')], max_length=10)),
                ('collaborators', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.note')),
            ],
        ),
    ]
