# Generated by Django 3.2.8 on 2022-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborations',
            name='permission',
            field=models.CharField(choices=[('READ_ONLY', 'READ_ONLY'), ('EDITOR', 'EDITOR')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
