# Generated by Django 3.2.8 on 2022-03-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborations',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to='note.note'),
        ),
    ]
