# Generated by Django 3.2.8 on 2022-02-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_collaborations_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborations',
            name='notes',
        ),
    ]
