# Generated by Django 3.2.8 on 2022-02-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_collaborators'),
        ('user', '0003_remove_collaborations_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborations',
            name='notes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.note'),
        ),
    ]
