# Generated by Django 3.2.8 on 2022-02-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_collaborations_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborations',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='collaborations',
            name='collaborators',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborations',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.note'),
        ),
    ]
